# Generated by tools/gen_sdk.sh from specs/docstudio-oss.json. DO NOT EDIT.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

if TYPE_CHECKING:
    from ..models.execution_message import ExecutionMessage


T = TypeVar("T", bound="ExecuteResponse")


@_attrs_define
class ExecuteResponse:
    """
    Attributes:
        message (ExecutionMessage):
    """

    message: ExecutionMessage
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        message = self.message.to_dict()

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "message": message,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.execution_message import ExecutionMessage

        d = dict(src_dict)
        message = ExecutionMessage.from_dict(d.pop("message"))

        execute_response = cls(
            message=message,
        )

        execute_response.additional_properties = d
        return execute_response

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
