# Generated by tools/gen_sdk.sh from specs/docstudio-oss.json. DO NOT EDIT.
from __future__ import annotations

from collections.abc import Mapping
from io import BytesIO
from typing import Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from .. import types
from ..types import UNSET, File, FileTypes, Unset

T = TypeVar("T", bound="ExecuteRequest")


@_attrs_define
class ExecuteRequest:
    """Subclasses the real serializer so every backend param arrives free.

    Attributes:
        custom_data (Any | Unset):
        files (list[File] | Unset):
        hitl_packet_id (None | str | Unset):
        hitl_queue_name (None | str | Unset):
        include_extracted_text (bool | Unset):  Default: False.
        include_metadata (bool | Unset):  Default: False.
        include_metrics (bool | Unset):  Default: False.
        llm_profile_id (None | str | Unset):
        presigned_urls (list[str] | Unset):
        tags (str | Unset): Comma-separated list of tag names (EX:'tag1,tag2-name,tag3_name') Default: ''.
        timeout (int | Unset):  Default: -1.
        use_file_history (bool | Unset):  Default: False.
    """

    custom_data: Any | Unset = UNSET
    files: list[File] | Unset = UNSET
    hitl_packet_id: None | str | Unset = UNSET
    hitl_queue_name: None | str | Unset = UNSET
    include_extracted_text: bool | Unset = False
    include_metadata: bool | Unset = False
    include_metrics: bool | Unset = False
    llm_profile_id: None | str | Unset = UNSET
    presigned_urls: list[str] | Unset = UNSET
    tags: str | Unset = ""
    timeout: int | Unset = -1
    use_file_history: bool | Unset = False
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        custom_data = self.custom_data

        files: list[FileTypes] | Unset = UNSET
        if not isinstance(self.files, Unset):
            files = []
            for files_item_data in self.files:
                files_item = files_item_data.to_tuple()

                files.append(files_item)

        hitl_packet_id: None | str | Unset
        if isinstance(self.hitl_packet_id, Unset):
            hitl_packet_id = UNSET
        else:
            hitl_packet_id = self.hitl_packet_id

        hitl_queue_name: None | str | Unset
        if isinstance(self.hitl_queue_name, Unset):
            hitl_queue_name = UNSET
        else:
            hitl_queue_name = self.hitl_queue_name

        include_extracted_text = self.include_extracted_text

        include_metadata = self.include_metadata

        include_metrics = self.include_metrics

        llm_profile_id: None | str | Unset
        if isinstance(self.llm_profile_id, Unset):
            llm_profile_id = UNSET
        else:
            llm_profile_id = self.llm_profile_id

        presigned_urls: list[str] | Unset = UNSET
        if not isinstance(self.presigned_urls, Unset):
            presigned_urls = self.presigned_urls

        tags = self.tags

        timeout = self.timeout

        use_file_history = self.use_file_history

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if custom_data is not UNSET:
            field_dict["custom_data"] = custom_data
        if files is not UNSET:
            field_dict["files"] = files
        if hitl_packet_id is not UNSET:
            field_dict["hitl_packet_id"] = hitl_packet_id
        if hitl_queue_name is not UNSET:
            field_dict["hitl_queue_name"] = hitl_queue_name
        if include_extracted_text is not UNSET:
            field_dict["include_extracted_text"] = include_extracted_text
        if include_metadata is not UNSET:
            field_dict["include_metadata"] = include_metadata
        if include_metrics is not UNSET:
            field_dict["include_metrics"] = include_metrics
        if llm_profile_id is not UNSET:
            field_dict["llm_profile_id"] = llm_profile_id
        if presigned_urls is not UNSET:
            field_dict["presigned_urls"] = presigned_urls
        if tags is not UNSET:
            field_dict["tags"] = tags
        if timeout is not UNSET:
            field_dict["timeout"] = timeout
        if use_file_history is not UNSET:
            field_dict["use_file_history"] = use_file_history

        return field_dict

    def to_multipart(self) -> types.RequestFiles:
        files: types.RequestFiles = []

        if not isinstance(self.custom_data, Unset):
            files.append(
                ("custom_data", (None, str(self.custom_data).encode(), "text/plain"))
            )

        if not isinstance(self.files, Unset):
            for files_item_element in self.files:
                files.append(("files", files_item_element.to_tuple()))

        if not isinstance(self.hitl_packet_id, Unset):
            if isinstance(self.hitl_packet_id, str):
                files.append(
                    (
                        "hitl_packet_id",
                        (None, str(self.hitl_packet_id).encode(), "text/plain"),
                    )
                )
            else:
                files.append(
                    (
                        "hitl_packet_id",
                        (None, str(self.hitl_packet_id).encode(), "text/plain"),
                    )
                )

        if not isinstance(self.hitl_queue_name, Unset):
            if isinstance(self.hitl_queue_name, str):
                files.append(
                    (
                        "hitl_queue_name",
                        (None, str(self.hitl_queue_name).encode(), "text/plain"),
                    )
                )
            else:
                files.append(
                    (
                        "hitl_queue_name",
                        (None, str(self.hitl_queue_name).encode(), "text/plain"),
                    )
                )

        if not isinstance(self.include_extracted_text, Unset):
            files.append(
                (
                    "include_extracted_text",
                    (None, str(self.include_extracted_text).encode(), "text/plain"),
                )
            )

        if not isinstance(self.include_metadata, Unset):
            files.append(
                (
                    "include_metadata",
                    (None, str(self.include_metadata).encode(), "text/plain"),
                )
            )

        if not isinstance(self.include_metrics, Unset):
            files.append(
                (
                    "include_metrics",
                    (None, str(self.include_metrics).encode(), "text/plain"),
                )
            )

        if not isinstance(self.llm_profile_id, Unset):
            if isinstance(self.llm_profile_id, str):
                files.append(
                    (
                        "llm_profile_id",
                        (None, str(self.llm_profile_id).encode(), "text/plain"),
                    )
                )
            else:
                files.append(
                    (
                        "llm_profile_id",
                        (None, str(self.llm_profile_id).encode(), "text/plain"),
                    )
                )

        if not isinstance(self.presigned_urls, Unset):
            for presigned_urls_item_element in self.presigned_urls:
                files.append(
                    (
                        "presigned_urls",
                        (None, str(presigned_urls_item_element).encode(), "text/plain"),
                    )
                )

        if not isinstance(self.tags, Unset):
            files.append(("tags", (None, str(self.tags).encode(), "text/plain")))

        if not isinstance(self.timeout, Unset):
            files.append(("timeout", (None, str(self.timeout).encode(), "text/plain")))

        if not isinstance(self.use_file_history, Unset):
            files.append(
                (
                    "use_file_history",
                    (None, str(self.use_file_history).encode(), "text/plain"),
                )
            )

        for prop_name, prop in self.additional_properties.items():
            files.append((prop_name, (None, str(prop).encode(), "text/plain")))

        return files

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        custom_data = d.pop("custom_data", UNSET)

        _files = d.pop("files", UNSET)
        files: list[File] | Unset = UNSET
        if _files is not UNSET:
            files = []
            for files_item_data in _files:
                files_item = File(payload=BytesIO(files_item_data))

                files.append(files_item)

        def _parse_hitl_packet_id(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        hitl_packet_id = _parse_hitl_packet_id(d.pop("hitl_packet_id", UNSET))

        def _parse_hitl_queue_name(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        hitl_queue_name = _parse_hitl_queue_name(d.pop("hitl_queue_name", UNSET))

        include_extracted_text = d.pop("include_extracted_text", UNSET)

        include_metadata = d.pop("include_metadata", UNSET)

        include_metrics = d.pop("include_metrics", UNSET)

        def _parse_llm_profile_id(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        llm_profile_id = _parse_llm_profile_id(d.pop("llm_profile_id", UNSET))

        presigned_urls = cast(list[str], d.pop("presigned_urls", UNSET))

        tags = d.pop("tags", UNSET)

        timeout = d.pop("timeout", UNSET)

        use_file_history = d.pop("use_file_history", UNSET)

        execute_request = cls(
            custom_data=custom_data,
            files=files,
            hitl_packet_id=hitl_packet_id,
            hitl_queue_name=hitl_queue_name,
            include_extracted_text=include_extracted_text,
            include_metadata=include_metadata,
            include_metrics=include_metrics,
            llm_profile_id=llm_profile_id,
            presigned_urls=presigned_urls,
            tags=tags,
            timeout=timeout,
            use_file_history=use_file_history,
        )

        execute_request.additional_properties = d
        return execute_request

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
