# Generated by tools/gen_sdk.sh from specs/docstudio-oss.json. DO NOT EDIT.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.file_result import FileResult


T = TypeVar("T", bound="StatusResponse")


@_attrs_define
class StatusResponse:
    """
    Attributes:
        status (str):
        message (list[FileResult] | None | Unset):
    """

    status: str
    message: list[FileResult] | None | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        status = self.status

        message: list[dict[str, Any]] | None | Unset
        if isinstance(self.message, Unset):
            message = UNSET
        elif isinstance(self.message, list):
            message = []
            for message_type_0_item_data in self.message:
                message_type_0_item = message_type_0_item_data.to_dict()
                message.append(message_type_0_item)

        else:
            message = self.message

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "status": status,
            }
        )
        if message is not UNSET:
            field_dict["message"] = message

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.file_result import FileResult

        d = dict(src_dict)
        status = d.pop("status")

        def _parse_message(data: object) -> list[FileResult] | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, list):
                    raise TypeError()
                message_type_0 = []
                _message_type_0 = data
                for message_type_0_item_data in _message_type_0:
                    message_type_0_item = FileResult.from_dict(message_type_0_item_data)

                    message_type_0.append(message_type_0_item)

                return message_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(list[FileResult] | None | Unset, data)

        message = _parse_message(d.pop("message", UNSET))

        status_response = cls(
            status=status,
            message=message,
        )

        status_response.additional_properties = d
        return status_response

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
