# Generated by tools/gen_sdk.sh from specs/docstudio-oss.json. DO NOT EDIT.
from http import HTTPStatus
from typing import Any
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...types import Response


def _get_kwargs(
    org_name: str,
    api_name: str,
) -> dict[str, Any]:

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/deployment/api/{org_name}/{api_name}/mcp/".format(
            org_name=quote(str(org_name), safe=""),
            api_name=quote(str(api_name), safe=""),
        ),
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Any | None:
    if response.status_code == 200:
        return None

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Any]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    org_name: str,
    api_name: str,
    *,
    client: AuthenticatedClient | Client,
) -> Response[Any]:
    """Refuse the SSE stream, but say who is here.

    Under Streamable HTTP a client issues GET to open a server-to-client
    SSE stream, and a server that offers none must answer 405 (spec rev
    2025-06-18). Nothing here pushes messages — every tool call is
    request/response — so 405 is the honest answer, and returning
    ``200 application/json`` instead would leave a conformant client
    parsing an identity document as an event stream.

    The body is kept anyway: uptime checks and humans with curl probe this
    path, and a 405 may carry one. It stays deliberately free of tenant
    detail — it reveals only that an MCP server is mounted here.

    ``JsonResponse``, not DRF's ``Response``, for the same reason ``post``
    uses it: a DRF response runs content negotiation, so a client sending
    ``Accept: text/html`` would be handed the browsable-API renderer.

    No ``Allow`` header is set here. RFC 9110 asks for one on a 405, but a
    handler cannot control it and pretending otherwise misleads a reader:
    DRF's ``finalize_response`` overwrites any handler-set value with
    ``self.allowed_methods`` (``GET, POST, HEAD, OPTIONS``, since this view
    defines both verbs), and ``RemoveAllowHeaderMiddleware`` — global in
    ``MIDDLEWARE`` — then pops the header from every response before it
    leaves the process. So a client sees no ``Allow`` at all; a test driving
    the view through ``APIRequestFactory`` bypasses that middleware and sees
    DRF's value.

    Args:
        org_name (str):
        api_name (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Any]
    """

    kwargs = _get_kwargs(
        org_name=org_name,
        api_name=api_name,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


async def asyncio_detailed(
    org_name: str,
    api_name: str,
    *,
    client: AuthenticatedClient | Client,
) -> Response[Any]:
    """Refuse the SSE stream, but say who is here.

    Under Streamable HTTP a client issues GET to open a server-to-client
    SSE stream, and a server that offers none must answer 405 (spec rev
    2025-06-18). Nothing here pushes messages — every tool call is
    request/response — so 405 is the honest answer, and returning
    ``200 application/json`` instead would leave a conformant client
    parsing an identity document as an event stream.

    The body is kept anyway: uptime checks and humans with curl probe this
    path, and a 405 may carry one. It stays deliberately free of tenant
    detail — it reveals only that an MCP server is mounted here.

    ``JsonResponse``, not DRF's ``Response``, for the same reason ``post``
    uses it: a DRF response runs content negotiation, so a client sending
    ``Accept: text/html`` would be handed the browsable-API renderer.

    No ``Allow`` header is set here. RFC 9110 asks for one on a 405, but a
    handler cannot control it and pretending otherwise misleads a reader:
    DRF's ``finalize_response`` overwrites any handler-set value with
    ``self.allowed_methods`` (``GET, POST, HEAD, OPTIONS``, since this view
    defines both verbs), and ``RemoveAllowHeaderMiddleware`` — global in
    ``MIDDLEWARE`` — then pops the header from every response before it
    leaves the process. So a client sees no ``Allow`` at all; a test driving
    the view through ``APIRequestFactory`` bypasses that middleware and sees
    DRF's value.

    Args:
        org_name (str):
        api_name (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Any]
    """

    kwargs = _get_kwargs(
        org_name=org_name,
        api_name=api_name,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)
