# Generated by tools/gen_sdk.sh from specs/docstudio-oss.json. DO NOT EDIT.
"""A client library for accessing Unstract API"""

from .client import AuthenticatedClient, Client

__all__ = (
    "AuthenticatedClient",
    "Client",
)
