# Generated by tools/gen_sdk.sh from specs/docstudio.json. DO NOT EDIT.
"""A client library for accessing Unstract Document Studio"""

from .client import AuthenticatedClient, Client

__all__ = (
    "AuthenticatedClient",
    "Client",
)
