# Generated by tools/gen_sdk.sh from specs/docstudio.json. DO NOT EDIT.
from http import HTTPStatus
from typing import Any
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error_response import ErrorResponse
from ...models.execute_request import ExecuteRequest
from ...models.execute_response import ExecuteResponse
from ...types import UNSET, Response, Unset


def _get_kwargs(
    org_name: str,
    api_name: str,
    *,
    body: ExecuteRequest | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/deployment/api/{org_name}/{api_name}/".format(
            org_name=quote(str(org_name), safe=""),
            api_name=quote(str(api_name), safe=""),
        ),
    }

    if not isinstance(body, Unset):
        _kwargs["files"] = body.to_multipart()

    headers["Content-Type"] = "multipart/form-data; boundary=+++"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> ErrorResponse | ExecuteResponse | None:
    if response.status_code == 200:
        response_200 = ExecuteResponse.from_dict(response.json())

        return response_200

    if response.status_code == 422:
        response_422 = ExecuteResponse.from_dict(response.json())

        return response_422

    if response.status_code == 500:
        response_500 = ErrorResponse.from_dict(response.json())

        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[ErrorResponse | ExecuteResponse]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    org_name: str,
    api_name: str,
    *,
    client: AuthenticatedClient,
    body: ExecuteRequest | Unset = UNSET,
) -> Response[ErrorResponse | ExecuteResponse]:
    """Execute an API deployment against one or more files.

    Args:
        org_name (str):
        api_name (str):
        body (ExecuteRequest | Unset): Subclasses the real serializer so every backend param
            arrives free.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ErrorResponse | ExecuteResponse]
    """

    kwargs = _get_kwargs(
        org_name=org_name,
        api_name=api_name,
        body=body,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    org_name: str,
    api_name: str,
    *,
    client: AuthenticatedClient,
    body: ExecuteRequest | Unset = UNSET,
) -> ErrorResponse | ExecuteResponse | None:
    """Execute an API deployment against one or more files.

    Args:
        org_name (str):
        api_name (str):
        body (ExecuteRequest | Unset): Subclasses the real serializer so every backend param
            arrives free.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ErrorResponse | ExecuteResponse
    """

    return sync_detailed(
        org_name=org_name,
        api_name=api_name,
        client=client,
        body=body,
    ).parsed


async def asyncio_detailed(
    org_name: str,
    api_name: str,
    *,
    client: AuthenticatedClient,
    body: ExecuteRequest | Unset = UNSET,
) -> Response[ErrorResponse | ExecuteResponse]:
    """Execute an API deployment against one or more files.

    Args:
        org_name (str):
        api_name (str):
        body (ExecuteRequest | Unset): Subclasses the real serializer so every backend param
            arrives free.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ErrorResponse | ExecuteResponse]
    """

    kwargs = _get_kwargs(
        org_name=org_name,
        api_name=api_name,
        body=body,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    org_name: str,
    api_name: str,
    *,
    client: AuthenticatedClient,
    body: ExecuteRequest | Unset = UNSET,
) -> ErrorResponse | ExecuteResponse | None:
    """Execute an API deployment against one or more files.

    Args:
        org_name (str):
        api_name (str):
        body (ExecuteRequest | Unset): Subclasses the real serializer so every backend param
            arrives free.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ErrorResponse | ExecuteResponse
    """

    return (
        await asyncio_detailed(
            org_name=org_name,
            api_name=api_name,
            client=client,
            body=body,
        )
    ).parsed
