# Generated by tools/gen_sdk.sh from specs/docstudio-oss.json. DO NOT EDIT.
from http import HTTPStatus
from typing import Any
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.acknowledged_response import AcknowledgedResponse
from ...models.error_response import ErrorResponse
from ...models.status_response import StatusResponse
from ...types import UNSET, Response, Unset


def _get_kwargs(
    org_name: str,
    api_name: str,
    *,
    execution_id: str,
    include_extracted_text: bool | Unset = False,
    include_metadata: bool | Unset = False,
    include_metrics: bool | Unset = False,
) -> dict[str, Any]:

    params: dict[str, Any] = {}

    params["execution_id"] = execution_id

    params["include_extracted_text"] = include_extracted_text

    params["include_metadata"] = include_metadata

    params["include_metrics"] = include_metrics

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/deployment/api/{org_name}/{api_name}/".format(
            org_name=quote(str(org_name), safe=""),
            api_name=quote(str(api_name), safe=""),
        ),
        "params": params,
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> AcknowledgedResponse | ErrorResponse | StatusResponse | None:
    if response.status_code == 200:
        response_200 = StatusResponse.from_dict(response.json())

        return response_200

    if response.status_code == 400:
        response_400 = ErrorResponse.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = ErrorResponse.from_dict(response.json())

        return response_401

    if response.status_code == 403:
        response_403 = ErrorResponse.from_dict(response.json())

        return response_403

    if response.status_code == 404:
        response_404 = ErrorResponse.from_dict(response.json())

        return response_404

    if response.status_code == 406:
        response_406 = AcknowledgedResponse.from_dict(response.json())

        return response_406

    if response.status_code == 422:
        response_422 = StatusResponse.from_dict(response.json())

        return response_422

    if response.status_code == 500:
        response_500 = StatusResponse.from_dict(response.json())

        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[AcknowledgedResponse | ErrorResponse | StatusResponse]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    org_name: str,
    api_name: str,
    *,
    client: AuthenticatedClient,
    execution_id: str,
    include_extracted_text: bool | Unset = False,
    include_metadata: bool | Unset = False,
    include_metrics: bool | Unset = False,
) -> Response[AcknowledgedResponse | ErrorResponse | StatusResponse]:
    """Read the result of a previously started execution.

    This read is one-shot: the first call that observes a completed execution acknowledges it and the
    stored result is discarded, so every later call for that execution answers 406. Poll while the
    execution is pending, and keep the payload of the call that returns it — it cannot be fetched again.

    A still-running execution answers 422 carrying its current `status`, so a polling loop should treat
    422 as the normal reply and stop on 200. Clients that raise on any non-2xx need to allow for that.

    Args:
        org_name (str):
        api_name (str):
        execution_id (str):
        include_extracted_text (bool | Unset):  Default: False.
        include_metadata (bool | Unset):  Default: False.
        include_metrics (bool | Unset):  Default: False.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[AcknowledgedResponse | ErrorResponse | StatusResponse]
    """

    kwargs = _get_kwargs(
        org_name=org_name,
        api_name=api_name,
        execution_id=execution_id,
        include_extracted_text=include_extracted_text,
        include_metadata=include_metadata,
        include_metrics=include_metrics,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    org_name: str,
    api_name: str,
    *,
    client: AuthenticatedClient,
    execution_id: str,
    include_extracted_text: bool | Unset = False,
    include_metadata: bool | Unset = False,
    include_metrics: bool | Unset = False,
) -> AcknowledgedResponse | ErrorResponse | StatusResponse | None:
    """Read the result of a previously started execution.

    This read is one-shot: the first call that observes a completed execution acknowledges it and the
    stored result is discarded, so every later call for that execution answers 406. Poll while the
    execution is pending, and keep the payload of the call that returns it — it cannot be fetched again.

    A still-running execution answers 422 carrying its current `status`, so a polling loop should treat
    422 as the normal reply and stop on 200. Clients that raise on any non-2xx need to allow for that.

    Args:
        org_name (str):
        api_name (str):
        execution_id (str):
        include_extracted_text (bool | Unset):  Default: False.
        include_metadata (bool | Unset):  Default: False.
        include_metrics (bool | Unset):  Default: False.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        AcknowledgedResponse | ErrorResponse | StatusResponse
    """

    return sync_detailed(
        org_name=org_name,
        api_name=api_name,
        client=client,
        execution_id=execution_id,
        include_extracted_text=include_extracted_text,
        include_metadata=include_metadata,
        include_metrics=include_metrics,
    ).parsed


async def asyncio_detailed(
    org_name: str,
    api_name: str,
    *,
    client: AuthenticatedClient,
    execution_id: str,
    include_extracted_text: bool | Unset = False,
    include_metadata: bool | Unset = False,
    include_metrics: bool | Unset = False,
) -> Response[AcknowledgedResponse | ErrorResponse | StatusResponse]:
    """Read the result of a previously started execution.

    This read is one-shot: the first call that observes a completed execution acknowledges it and the
    stored result is discarded, so every later call for that execution answers 406. Poll while the
    execution is pending, and keep the payload of the call that returns it — it cannot be fetched again.

    A still-running execution answers 422 carrying its current `status`, so a polling loop should treat
    422 as the normal reply and stop on 200. Clients that raise on any non-2xx need to allow for that.

    Args:
        org_name (str):
        api_name (str):
        execution_id (str):
        include_extracted_text (bool | Unset):  Default: False.
        include_metadata (bool | Unset):  Default: False.
        include_metrics (bool | Unset):  Default: False.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[AcknowledgedResponse | ErrorResponse | StatusResponse]
    """

    kwargs = _get_kwargs(
        org_name=org_name,
        api_name=api_name,
        execution_id=execution_id,
        include_extracted_text=include_extracted_text,
        include_metadata=include_metadata,
        include_metrics=include_metrics,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    org_name: str,
    api_name: str,
    *,
    client: AuthenticatedClient,
    execution_id: str,
    include_extracted_text: bool | Unset = False,
    include_metadata: bool | Unset = False,
    include_metrics: bool | Unset = False,
) -> AcknowledgedResponse | ErrorResponse | StatusResponse | None:
    """Read the result of a previously started execution.

    This read is one-shot: the first call that observes a completed execution acknowledges it and the
    stored result is discarded, so every later call for that execution answers 406. Poll while the
    execution is pending, and keep the payload of the call that returns it — it cannot be fetched again.

    A still-running execution answers 422 carrying its current `status`, so a polling loop should treat
    422 as the normal reply and stop on 200. Clients that raise on any non-2xx need to allow for that.

    Args:
        org_name (str):
        api_name (str):
        execution_id (str):
        include_extracted_text (bool | Unset):  Default: False.
        include_metadata (bool | Unset):  Default: False.
        include_metrics (bool | Unset):  Default: False.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        AcknowledgedResponse | ErrorResponse | StatusResponse
    """

    return (
        await asyncio_detailed(
            org_name=org_name,
            api_name=api_name,
            client=client,
            execution_id=execution_id,
            include_extracted_text=include_extracted_text,
            include_metadata=include_metadata,
            include_metrics=include_metrics,
        )
    ).parsed
