# Generated by tools/gen_sdk.sh from specs/docstudio-oss.json. DO NOT EDIT.
from http import HTTPStatus
from typing import Any
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error_response import ErrorResponse
from ...models.status_response import StatusResponse
from ...types import UNSET, Response, Unset


def _get_kwargs(
    org_name: str,
    api_name: str,
    *,
    execution_id: str,
    include_extracted_text: bool | Unset = False,
    include_metadata: bool | Unset = False,
    include_metrics: bool | Unset = False,
) -> dict[str, Any]:

    params: dict[str, Any] = {}

    params["execution_id"] = execution_id

    params["include_extracted_text"] = include_extracted_text

    params["include_metadata"] = include_metadata

    params["include_metrics"] = include_metrics

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/deployment/api/{org_name}/{api_name}/".format(
            org_name=quote(str(org_name), safe=""),
            api_name=quote(str(api_name), safe=""),
        ),
        "params": params,
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> ErrorResponse | StatusResponse | None:
    if response.status_code == 200:
        response_200 = StatusResponse.from_dict(response.json())

        return response_200

    if response.status_code == 406:
        response_406 = ErrorResponse.from_dict(response.json())

        return response_406

    if response.status_code == 422:
        response_422 = StatusResponse.from_dict(response.json())

        return response_422

    if response.status_code == 500:
        response_500 = ErrorResponse.from_dict(response.json())

        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[ErrorResponse | StatusResponse]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    org_name: str,
    api_name: str,
    *,
    client: AuthenticatedClient,
    execution_id: str,
    include_extracted_text: bool | Unset = False,
    include_metadata: bool | Unset = False,
    include_metrics: bool | Unset = False,
) -> Response[ErrorResponse | StatusResponse]:
    """Poll the status of a previously started execution.

    Args:
        org_name (str):
        api_name (str):
        execution_id (str):
        include_extracted_text (bool | Unset):  Default: False.
        include_metadata (bool | Unset):  Default: False.
        include_metrics (bool | Unset):  Default: False.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ErrorResponse | StatusResponse]
    """

    kwargs = _get_kwargs(
        org_name=org_name,
        api_name=api_name,
        execution_id=execution_id,
        include_extracted_text=include_extracted_text,
        include_metadata=include_metadata,
        include_metrics=include_metrics,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    org_name: str,
    api_name: str,
    *,
    client: AuthenticatedClient,
    execution_id: str,
    include_extracted_text: bool | Unset = False,
    include_metadata: bool | Unset = False,
    include_metrics: bool | Unset = False,
) -> ErrorResponse | StatusResponse | None:
    """Poll the status of a previously started execution.

    Args:
        org_name (str):
        api_name (str):
        execution_id (str):
        include_extracted_text (bool | Unset):  Default: False.
        include_metadata (bool | Unset):  Default: False.
        include_metrics (bool | Unset):  Default: False.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ErrorResponse | StatusResponse
    """

    return sync_detailed(
        org_name=org_name,
        api_name=api_name,
        client=client,
        execution_id=execution_id,
        include_extracted_text=include_extracted_text,
        include_metadata=include_metadata,
        include_metrics=include_metrics,
    ).parsed


async def asyncio_detailed(
    org_name: str,
    api_name: str,
    *,
    client: AuthenticatedClient,
    execution_id: str,
    include_extracted_text: bool | Unset = False,
    include_metadata: bool | Unset = False,
    include_metrics: bool | Unset = False,
) -> Response[ErrorResponse | StatusResponse]:
    """Poll the status of a previously started execution.

    Args:
        org_name (str):
        api_name (str):
        execution_id (str):
        include_extracted_text (bool | Unset):  Default: False.
        include_metadata (bool | Unset):  Default: False.
        include_metrics (bool | Unset):  Default: False.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ErrorResponse | StatusResponse]
    """

    kwargs = _get_kwargs(
        org_name=org_name,
        api_name=api_name,
        execution_id=execution_id,
        include_extracted_text=include_extracted_text,
        include_metadata=include_metadata,
        include_metrics=include_metrics,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    org_name: str,
    api_name: str,
    *,
    client: AuthenticatedClient,
    execution_id: str,
    include_extracted_text: bool | Unset = False,
    include_metadata: bool | Unset = False,
    include_metrics: bool | Unset = False,
) -> ErrorResponse | StatusResponse | None:
    """Poll the status of a previously started execution.

    Args:
        org_name (str):
        api_name (str):
        execution_id (str):
        include_extracted_text (bool | Unset):  Default: False.
        include_metadata (bool | Unset):  Default: False.
        include_metrics (bool | Unset):  Default: False.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ErrorResponse | StatusResponse
    """

    return (
        await asyncio_detailed(
            org_name=org_name,
            api_name=api_name,
            client=client,
            execution_id=execution_id,
            include_extracted_text=include_extracted_text,
            include_metadata=include_metadata,
            include_metrics=include_metrics,
        )
    ).parsed
