# Generated by tools/gen_sdk.sh from specs/docstudio-oss.json. DO NOT EDIT.
from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast
from uuid import UUID

from attrs import define as _attrs_define
from attrs import field as _attrs_field

if TYPE_CHECKING:
    from ..models.api_deployment_summary_last_5_run_statuses_item import (
        APIDeploymentSummaryLast5RunStatusesItem,
    )


T = TypeVar("T", bound="APIDeploymentSummary")


@_attrs_define
class APIDeploymentSummary:
    """One API deployment, as it appears in an organisation's listing.

    `api_name` and `api_endpoint` are what an execution call needs;
    `display_name` and `description` say what the deployment is for.

        Attributes:
            api_endpoint (str):
            api_name (str):
            co_owners_count (int):
            created_by (int | None):
            created_by_email (None | str): Get the email of the creator.
            description (str):
            display_name (str):
            id (UUID):
            is_active (bool):
            is_owner (bool):
            last_5_run_statuses (list[APIDeploymentSummaryLast5RunStatusesItem]): Fetch the last 5 execution statuses with
                timestamps for this API deployment.
            last_run_time (None | str):
            run_count (int):
            workflow (UUID):
            workflow_name (str):
    """

    api_endpoint: str
    api_name: str
    co_owners_count: int
    created_by: int | None
    created_by_email: None | str
    description: str
    display_name: str
    id: UUID
    is_active: bool
    is_owner: bool
    last_5_run_statuses: list[APIDeploymentSummaryLast5RunStatusesItem]
    last_run_time: None | str
    run_count: int
    workflow: UUID
    workflow_name: str
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        api_endpoint = self.api_endpoint

        api_name = self.api_name

        co_owners_count = self.co_owners_count

        created_by: int | None
        created_by = self.created_by

        created_by_email: None | str
        created_by_email = self.created_by_email

        description = self.description

        display_name = self.display_name

        id = str(self.id)

        is_active = self.is_active

        is_owner = self.is_owner

        last_5_run_statuses = []
        for last_5_run_statuses_item_data in self.last_5_run_statuses:
            last_5_run_statuses_item = last_5_run_statuses_item_data.to_dict()
            last_5_run_statuses.append(last_5_run_statuses_item)

        last_run_time: None | str
        last_run_time = self.last_run_time

        run_count = self.run_count

        workflow = str(self.workflow)

        workflow_name = self.workflow_name

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "api_endpoint": api_endpoint,
                "api_name": api_name,
                "co_owners_count": co_owners_count,
                "created_by": created_by,
                "created_by_email": created_by_email,
                "description": description,
                "display_name": display_name,
                "id": id,
                "is_active": is_active,
                "is_owner": is_owner,
                "last_5_run_statuses": last_5_run_statuses,
                "last_run_time": last_run_time,
                "run_count": run_count,
                "workflow": workflow,
                "workflow_name": workflow_name,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.api_deployment_summary_last_5_run_statuses_item import (
            APIDeploymentSummaryLast5RunStatusesItem,
        )

        d = dict(src_dict)
        api_endpoint = d.pop("api_endpoint")

        api_name = d.pop("api_name")

        co_owners_count = d.pop("co_owners_count")

        def _parse_created_by(data: object) -> int | None:
            if data is None:
                return data
            return cast(int | None, data)

        created_by = _parse_created_by(d.pop("created_by"))

        def _parse_created_by_email(data: object) -> None | str:
            if data is None:
                return data
            return cast(None | str, data)

        created_by_email = _parse_created_by_email(d.pop("created_by_email"))

        description = d.pop("description")

        display_name = d.pop("display_name")

        id = UUID(d.pop("id"))

        is_active = d.pop("is_active")

        is_owner = d.pop("is_owner")

        last_5_run_statuses = []
        _last_5_run_statuses = d.pop("last_5_run_statuses")
        for last_5_run_statuses_item_data in _last_5_run_statuses:
            last_5_run_statuses_item = (
                APIDeploymentSummaryLast5RunStatusesItem.from_dict(
                    last_5_run_statuses_item_data
                )
            )

            last_5_run_statuses.append(last_5_run_statuses_item)

        def _parse_last_run_time(data: object) -> None | str:
            if data is None:
                return data
            return cast(None | str, data)

        last_run_time = _parse_last_run_time(d.pop("last_run_time"))

        run_count = d.pop("run_count")

        workflow = UUID(d.pop("workflow"))

        workflow_name = d.pop("workflow_name")

        api_deployment_summary = cls(
            api_endpoint=api_endpoint,
            api_name=api_name,
            co_owners_count=co_owners_count,
            created_by=created_by,
            created_by_email=created_by_email,
            description=description,
            display_name=display_name,
            id=id,
            is_active=is_active,
            is_owner=is_owner,
            last_5_run_statuses=last_5_run_statuses,
            last_run_time=last_run_time,
            run_count=run_count,
            workflow=workflow,
            workflow_name=workflow_name,
        )

        api_deployment_summary.additional_properties = d
        return api_deployment_summary

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
