# Generated by tools/gen_sdk.sh from specs/docstudio-oss.json. DO NOT EDIT.
from typing import Literal

ApiKeyPermission = Literal["full_access", "read", "read_write"]

API_KEY_PERMISSION_VALUES: set[ApiKeyPermission] = {
    "full_access",
    "read",
    "read_write",
}


def check_api_key_permission(value: str) -> ApiKeyPermission:
    if value in API_KEY_PERMISSION_VALUES:
        return value
    raise TypeError(
        f"Unexpected value {value!r}. Expected one of {API_KEY_PERMISSION_VALUES!r}"
    )
