# Generated by tools/gen_sdk.sh from specs/docstudio-oss.json. DO NOT EDIT.
from typing import Literal

ErrorType = Literal["client_error", "server_error", "validation_error"]

ERROR_TYPE_VALUES: set[ErrorType] = {
    "client_error",
    "server_error",
    "validation_error",
}


def check_error_type(value: str) -> ErrorType:
    if value in ERROR_TYPE_VALUES:
        return value
    raise TypeError(
        f"Unexpected value {value!r}. Expected one of {ERROR_TYPE_VALUES!r}"
    )
