# Generated by tools/gen_sdk.sh from specs/docstudio-oss.json. DO NOT EDIT.
from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.api_key_permission import ApiKeyPermission, check_api_key_permission

T = TypeVar("T", bound="WhoAmIResponse")


@_attrs_define
class WhoAmIResponse:
    """The organisation a platform API key belongs to, and what it may do.

    Attributes:
        key_name (str): The key's name, as it was minted.
        organization_id (str): The organisation's identifier, as it appears in web-app URLs and in every organisation-
            scoped API path.
        organization_name (str): The organisation's display name.
        permission (ApiKeyPermission): * `read` - Read
            * `read_write` - Read/Write
            * `full_access` - Full Access
    """

    key_name: str
    organization_id: str
    organization_name: str
    permission: ApiKeyPermission
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        key_name = self.key_name

        organization_id = self.organization_id

        organization_name = self.organization_name

        permission: str = self.permission

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "key_name": key_name,
                "organization_id": organization_id,
                "organization_name": organization_name,
                "permission": permission,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        key_name = d.pop("key_name")

        organization_id = d.pop("organization_id")

        organization_name = d.pop("organization_name")

        permission = check_api_key_permission(d.pop("permission"))

        who_am_i_response = cls(
            key_name=key_name,
            organization_id=organization_id,
            organization_name=organization_name,
            permission=permission,
        )

        who_am_i_response.additional_properties = d
        return who_am_i_response

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
