#!/usr/bin/env bash
# Regenerate the transport layer from the committed OpenAPI spec.
#
# The generated tree is committed but NEVER hand-edited: regeneration overwrites
# it wholesale, so a fix applied there is lost on the next run. Fixes belong in
# the facade (client.py) or upstream in the spec.
#
# The spec itself is produced by the backend that serves these endpoints
# (`manage.py generate_docstudio_spec`); refresh it from there rather than
# editing it here, and move SPEC_SOURCE below in the same commit.
#
# `git add -N` first: a diff alone cannot see a file the generator has newly
# created, which is exactly what a spec growing an endpoint does.
#
#   ./tools/gen_sdk.sh \
#     && git add -N -- src/unstract/api_deployments/sdk_docstudio \
#     && git diff --stat -- src/unstract/api_deployments/sdk_docstudio
#
# Where specs/docstudio-oss.json was copied from. Without a revision recorded,
# nothing distinguishes a current copy from one the backend has moved past, and
# both this script and the drift gate report clean either way.
#
#   SPEC_SOURCE: Zipstack/unstract specs/docstudio-oss.json
#                @ eddd4b746765c77a3d6f64b428fd35d2261e60e7
#                sha256 e453d4f7444d3757a24a1da73373b11c3d362ceb2d7e13e8658a5b3c068b86f5
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV="$REPO/.gen-venv"
# The generator shells out to ruff for its own post-processing. Without this it
# finds whatever ruff the caller happens to have, or none, and reports the miss
# as a warning -- which the gate below reads as an unparsable spec.
export PATH="$VENV/bin:$PATH"
OUT="src/unstract/api_deployments/sdk_docstudio"
# Pinned: unpinned, a generator upgrade and a spec change produce the same diff,
# and the drift gate can no longer tell them apart.
GENERATOR="openapi-python-client==0.29.0"

if [ ! -x "$VENV/bin/openapi-python-client" ]; then
  uv venv "$VENV"
  uv pip install --python "$VENV/bin/python" "$GENERATOR"
fi

want="${GENERATOR#*==}"
have="$("$VENV/bin/openapi-python-client" --version | awk '{print $NF}')"
if [ "$have" != "$want" ]; then
  echo "generator is $have, expected $want — reinstalling" >&2
  uv pip install --python "$VENV/bin/python" "$GENERATOR"
fi

rm -rf "${REPO:?}/$OUT"
log="$(mktemp)"
trap 'rm -f "$log"' EXIT
(cd "$REPO" && "$VENV/bin/openapi-python-client" generate \
    --path "$REPO/specs/docstudio-oss.json" --output-path "$REPO/$OUT" \
    --config "$REPO/tools/openapi-client.yaml" --overwrite --meta none) 2>&1 | tee "$log"

# The generator downgrades a schema it cannot parse to a warning, drops
# the endpoint or model it belongs to, writes the rest and exits 0. The
# result is a client missing an operation and a spec that still looks fine.
if grep -qi warning "$log"; then
  echo "the generator reported a problem above and still exited 0; whatever it could not parse is missing from the output" >&2
  exit 1
fi

# Stamp every file, so the rule survives contact with a reader who arrived via
# grep rather than via this script.
header='# Generated by tools/gen_sdk.sh from specs/docstudio-oss.json. DO NOT EDIT.'
find "$REPO/$OUT" -name '*.py' -print0 | while IFS= read -r -d '' f; do
  printf '%s\n%s\n' "$header" "$(cat "$f")" > "$f.tmp" && mv "$f.tmp" "$f"
done

echo "generated $OUT ($(find "$REPO/$OUT" -name '*.py' | wc -l) files)"
