# Generated by tools/gen_sdk.sh from specs/docstudio-oss.json. DO NOT EDIT.
from http import HTTPStatus
from typing import Any, cast

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.platform_key_error import PlatformKeyError
from ...models.who_am_i_response import WhoAmIResponse
from ...types import Response


def _get_kwargs() -> dict[str, Any]:

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/api/v1/unstract/whoami/",
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Any | PlatformKeyError | WhoAmIResponse | None:
    if response.status_code == 200:
        response_200 = WhoAmIResponse.from_dict(response.json())

        return response_200

    if response.status_code == 401:
        response_401 = PlatformKeyError.from_dict(response.json())

        return response_401

    if response.status_code == 500:
        response_500 = cast(Any, None)
        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Any | PlatformKeyError | WhoAmIResponse]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient,
) -> Response[Any | PlatformKeyError | WhoAmIResponse]:
    """Resolve the organisation a platform key belongs to

     Takes a platform API key and nothing else: the organisation is read from the key itself, so this
    route carries no organisation segment. Call it once and store `organization_id`; every other
    endpoint takes it as a path segment.

    An API deployment key is rejected as unauthenticated.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Any | PlatformKeyError | WhoAmIResponse]
    """

    kwargs = _get_kwargs()

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient,
) -> Any | PlatformKeyError | WhoAmIResponse | None:
    """Resolve the organisation a platform key belongs to

     Takes a platform API key and nothing else: the organisation is read from the key itself, so this
    route carries no organisation segment. Call it once and store `organization_id`; every other
    endpoint takes it as a path segment.

    An API deployment key is rejected as unauthenticated.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Any | PlatformKeyError | WhoAmIResponse
    """

    return sync_detailed(
        client=client,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient,
) -> Response[Any | PlatformKeyError | WhoAmIResponse]:
    """Resolve the organisation a platform key belongs to

     Takes a platform API key and nothing else: the organisation is read from the key itself, so this
    route carries no organisation segment. Call it once and store `organization_id`; every other
    endpoint takes it as a path segment.

    An API deployment key is rejected as unauthenticated.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Any | PlatformKeyError | WhoAmIResponse]
    """

    kwargs = _get_kwargs()

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient,
) -> Any | PlatformKeyError | WhoAmIResponse | None:
    """Resolve the organisation a platform key belongs to

     Takes a platform API key and nothing else: the organisation is read from the key itself, so this
    route carries no organisation segment. Call it once and store `organization_id`; every other
    endpoint takes it as a path segment.

    An API deployment key is rejected as unauthenticated.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Any | PlatformKeyError | WhoAmIResponse
    """

    return (
        await asyncio_detailed(
            client=client,
        )
    ).parsed
