# Generated by tools/gen_sdk.sh from specs/docstudio-oss.json. DO NOT EDIT.
from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote
from uuid import UUID

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error_response import ErrorResponse
from ...models.paginated_api_deployment_summary_list import (
    PaginatedAPIDeploymentSummaryList,
)
from ...models.platform_key_error import PlatformKeyError
from ...types import UNSET, Response, Unset


def _get_kwargs(
    org_id: str,
    *,
    api_name: str | Unset = UNSET,
    ordering: str | Unset = UNSET,
    page: int | Unset = UNSET,
    page_size: int | Unset = UNSET,
    search: str | Unset = UNSET,
    workflow: UUID | Unset = UNSET,
) -> dict[str, Any]:

    params: dict[str, Any] = {}

    params["api_name"] = api_name

    params["ordering"] = ordering

    params["page"] = page

    params["page_size"] = page_size

    params["search"] = search

    json_workflow: str | Unset = UNSET
    if not isinstance(workflow, Unset):
        json_workflow = str(workflow)
    params["workflow"] = json_workflow

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/api/v1/unstract/{org_id}/api/deployment/".format(
            org_id=quote(str(org_id), safe=""),
        ),
        "params": params,
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Any | ErrorResponse | PaginatedAPIDeploymentSummaryList | PlatformKeyError | None:
    if response.status_code == 200:
        response_200 = PaginatedAPIDeploymentSummaryList.from_dict(response.json())

        return response_200

    if response.status_code == 400:
        response_400 = ErrorResponse.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = PlatformKeyError.from_dict(response.json())

        return response_401

    if response.status_code == 403:
        response_403 = PlatformKeyError.from_dict(response.json())

        return response_403

    if response.status_code == 500:
        response_500 = cast(Any, None)
        return response_500

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[
    Any | ErrorResponse | PaginatedAPIDeploymentSummaryList | PlatformKeyError
]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    org_id: str,
    *,
    client: AuthenticatedClient,
    api_name: str | Unset = UNSET,
    ordering: str | Unset = UNSET,
    page: int | Unset = UNSET,
    page_size: int | Unset = UNSET,
    search: str | Unset = UNSET,
    workflow: UUID | Unset = UNSET,
) -> Response[
    Any | ErrorResponse | PaginatedAPIDeploymentSummaryList | PlatformKeyError
]:
    """List an organisation's API deployments

     Lists what an organisation has deployed, authenticated by a platform API key that belongs to it.

    A deployment key is not part of this listing; executing a deployment still needs one.

    Ordered by most recent run first, then by identifier, so paging is stable.

    Args:
        org_id (str):
        api_name (str | Unset):
        ordering (str | Unset):
        page (int | Unset):
        page_size (int | Unset):
        search (str | Unset):
        workflow (UUID | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Any | ErrorResponse | PaginatedAPIDeploymentSummaryList | PlatformKeyError]
    """

    kwargs = _get_kwargs(
        org_id=org_id,
        api_name=api_name,
        ordering=ordering,
        page=page,
        page_size=page_size,
        search=search,
        workflow=workflow,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    org_id: str,
    *,
    client: AuthenticatedClient,
    api_name: str | Unset = UNSET,
    ordering: str | Unset = UNSET,
    page: int | Unset = UNSET,
    page_size: int | Unset = UNSET,
    search: str | Unset = UNSET,
    workflow: UUID | Unset = UNSET,
) -> Any | ErrorResponse | PaginatedAPIDeploymentSummaryList | PlatformKeyError | None:
    """List an organisation's API deployments

     Lists what an organisation has deployed, authenticated by a platform API key that belongs to it.

    A deployment key is not part of this listing; executing a deployment still needs one.

    Ordered by most recent run first, then by identifier, so paging is stable.

    Args:
        org_id (str):
        api_name (str | Unset):
        ordering (str | Unset):
        page (int | Unset):
        page_size (int | Unset):
        search (str | Unset):
        workflow (UUID | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Any | ErrorResponse | PaginatedAPIDeploymentSummaryList | PlatformKeyError
    """

    return sync_detailed(
        org_id=org_id,
        client=client,
        api_name=api_name,
        ordering=ordering,
        page=page,
        page_size=page_size,
        search=search,
        workflow=workflow,
    ).parsed


async def asyncio_detailed(
    org_id: str,
    *,
    client: AuthenticatedClient,
    api_name: str | Unset = UNSET,
    ordering: str | Unset = UNSET,
    page: int | Unset = UNSET,
    page_size: int | Unset = UNSET,
    search: str | Unset = UNSET,
    workflow: UUID | Unset = UNSET,
) -> Response[
    Any | ErrorResponse | PaginatedAPIDeploymentSummaryList | PlatformKeyError
]:
    """List an organisation's API deployments

     Lists what an organisation has deployed, authenticated by a platform API key that belongs to it.

    A deployment key is not part of this listing; executing a deployment still needs one.

    Ordered by most recent run first, then by identifier, so paging is stable.

    Args:
        org_id (str):
        api_name (str | Unset):
        ordering (str | Unset):
        page (int | Unset):
        page_size (int | Unset):
        search (str | Unset):
        workflow (UUID | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Any | ErrorResponse | PaginatedAPIDeploymentSummaryList | PlatformKeyError]
    """

    kwargs = _get_kwargs(
        org_id=org_id,
        api_name=api_name,
        ordering=ordering,
        page=page,
        page_size=page_size,
        search=search,
        workflow=workflow,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    org_id: str,
    *,
    client: AuthenticatedClient,
    api_name: str | Unset = UNSET,
    ordering: str | Unset = UNSET,
    page: int | Unset = UNSET,
    page_size: int | Unset = UNSET,
    search: str | Unset = UNSET,
    workflow: UUID | Unset = UNSET,
) -> Any | ErrorResponse | PaginatedAPIDeploymentSummaryList | PlatformKeyError | None:
    """List an organisation's API deployments

     Lists what an organisation has deployed, authenticated by a platform API key that belongs to it.

    A deployment key is not part of this listing; executing a deployment still needs one.

    Ordered by most recent run first, then by identifier, so paging is stable.

    Args:
        org_id (str):
        api_name (str | Unset):
        ordering (str | Unset):
        page (int | Unset):
        page_size (int | Unset):
        search (str | Unset):
        workflow (UUID | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Any | ErrorResponse | PaginatedAPIDeploymentSummaryList | PlatformKeyError
    """

    return (
        await asyncio_detailed(
            org_id=org_id,
            client=client,
            api_name=api_name,
            ordering=ordering,
            page=page,
            page_size=page_size,
            search=search,
            workflow=workflow,
        )
    ).parsed
